#! /bin/bash
if [ "$EUID" -ne 0 ]; then
        echo "you are not root, come back when you are, BYE"
        exit
fi

p1=$1
if [ -n "$p1" ]; then
	if [ "$p1" == "-t" ]; then
        	while getopts t: option; do
                	case ${option}
                	in
                        	t) TYPE=${OPTARG};;
                	esac
        	done
		if [ "$TYPE" == "MX" ]; then
        		echo "mx"
                	ZONE="`echo $5`"
                	echo "@		IN	MX	$3.$5" >> /etc/bind/zones/db.$ZONE
                	echo "$3	IN	A	$4" >> /etc/bind/zones/db.$ZONE

			Serial=$(grep 'Serial' /etc/bind/db.$ZONE)
			SerialNumber=$(echo $Serial| sed 's/[^0-9]*//g')
			((SerialNumber++))
			s1='                            '"$SerialNumber"'        ;Serial'
			sed -i "s/.*Serial.*/\t\t $s1/g" /etc/bind/zones/db.$ZONE

        	elif [ "$TYPE" == "CNAME" ]
        	then
                	echo "cname"
                	ZONE="`echo $4`"
                	echo "$3	IN	CNAME	$4" >> /etc/bind/zones/db.$ZONE

                	Serial=$(grep 'Serial' /etc/bind/db.$ZONE)
                	SerialNumber=$(echo $Serial| sed 's/[^0-9]*//g')
                	((SerialNumber++))
                	s1='                            '"$SerialNumber"'        ;Serial'
                	sed -i "s/.*Serial.*/\t\t $s1/g" /etc/bind/zones/db.$ZONE


        	elif [ "$TYPE" == "A" ]
        	then
			echo "a"
                	ZONE="`echo $5`"
                	echo "$3	IN	A	$4" >> /etc/bind/zones/db.$ZONE

                	Serial=$(grep 'Serial' /etc/bind/zones/db.$ZONE)
                	SerialNumber=$(echo $Serial| sed 's/[^0-9]*//g')
                	((SerialNumber++))
                	s1='                            '"$SerialNumber"'        ;Serial'
                	sed -i "s/.*Serial.*/\t\t $s1/g" /etc/bind/zones/db.$ZONE
		fi
		else
        		ZONE="`echo $3`"
        		echo "$param1	IN	A	$2" >> /etc/bind/zones/db.$ZONE
        		#serial++
        		Serial=$(grep 'Serial' /etc/bind/zones/db.$ZONE)
        		SerialNumber=$(echo $Serial| sed 's/[^0-9]*//g')
        		((SerialNumber++))
        		s1='                            '"$SerialNumber"'        ;Serial'
        		sed -i "s/.*Serial.*/\t\t $s1/g" /etc/bind/zones/db.$ZONE

		fi



	systemctl restart bind9
else
	echo -e "invalid"
fi
