#!/bin/bash
if [[ $EUID -ne 0 ]]; then
	   echo This script must be run as root
	      exit 0;
fi

if [ -z $1 ]
then
	echo needs a subdomain
	exit 0;
fi

cat <<EOF>> /etc/bind/named.conf.mrt-zones
zone "$1.jonas-peeters.sb.uclllabs.be"  {
        type master;
        file "/etc/bind/db.$1.jonas-peeters.sb.uclllabs.be";
		
};
EOF
cat <<EOF>> /etc/bind/db.$1.jonas-peeters.sb.uclllabs.be
;
; BIND data file for local loopback interface
;
\$TTL    2M
@       IN      SOA     ns.$1.jonas-peeters.sb.uclllabs.be. root.$1.jonas-peeters.sb.uclllabs.be. (
2 ; Serial
                             2M         ; Refresh
                             2M         ; Retry
                             2M         ; Expire
                             2M )       ; Negative Cache TTL
;
@       IN      NS     ns.jonas-peeters.sb.uclllabs.be.
@	IN	A	193.191.177.163
ns	IN	A	193.191.177.163
EOF
echo -e "$1	IN	NS	ns.jonas-peeters.sb.uclllabs.be." >> /etc/bind/db.jonas-peeters.sb.uclllabs.be
i=$(grep Serial /etc/bind/db.jonas-peeters.sb.uclllabs.be | cut -d' ' -f1)
echo $i
j=$((i+1))
echo $j
sed -i "s/$i ; Serial/$j ; Serial/" /etc/bind/db.jonas-peeters.sb.uclllabs.be
rndc reload
systemctl restart bind9
