#!/bin/bash

# Check if root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Check input for zone name
if [[ "$1" != "" ]]; then
  domain="$1"
	echo "Creating a zone file for $domain"
else
  echo "No domain name was given"
  exit 0
fi

# New line in mrt-zones file
echo "" >> /etc/bind/named.conf.mrt-zones

# Append config for domain given
echo "// $domain config"  >> /etc/bind/named.conf.mrt-zones
echo "zone $domain.jonas-peeters.sb.uclllabs.be. {
	type master;
	file \"/etc/bind/zones/master/db.$domain.jonas-peeters.sb.uclllabs.be\";
};" >> /etc/bind/named.conf.mrt-zones

echo "Appended config for $domain to mrt-zones"

# Create zonefile

echo  "\$TTL 4800
@	IN	SOA	ns.$domain.jonas-peeters.sb.uclllabs.be. root.ns.jonas-peeters.sb.uclllabs.be. (
			20005		; Serial
			604800		; Refresh
			600		; Retry
			600		; Expire
			604800 )	; Negative Cache TTl
;Name Servers
@	IN	NS	ns.$domain.jonas-peeters.sb.uclllabs.be.
@	IN	NS	ns.jonas-peeters.sb.uclllabs.be.
;Hosts
ns	IN	A	193.191.177.167
@	IN	A	193.191.177.167" > /etc/bind/zones/master/db.$domain.jonas-peeters.sb.uclllabs.be

echo "db.$domain.jonas-peeters.sb.uclllabs.be CREATED"

# Delegation: NS-record for subzone in main zone

echo "$domain                                IN      NS      ns.jonas-peeters.sb.uclllabs.be." >> /etc/bind/zones/master/db.jonas-peeters.sb.uclllabs.be

echo "Added NS-record for $domain"

# Get current serial from main zone file 

serial=$(grep "Serial" /etc/bind/zones/master/db.jonas-peeters.sb.uclllabs.be | tr -s [:blank] | cut -d \; -f 1)


last=$(grep "Serial" /etc/bind/zones/master/db.jonas-peeters.sb.uclllabs.be | tr -dc '0-9')
new=$((last + 1))
sed -i "s/.*Serial.*/\t\t	 $new	 ;Serial/g" /etc/bind/zones/master/db.jonas-peeters.sb.uclllabs.be


# Restart bind9

systemctl reload bind9
systemctl status bind9
